### ISSUE TITLE
dpm with list of multiply imputed dataframes

### ISSUE THREAD

**Issue by sccollitt** [jacob-long/dpm#4]
Hi (sorry but to preface I have not written a github issue before): I have some imputed dataframes in a list and I'd like to run dpm over them with:

`dpm.pidideo.news.out <- lapply(a.out.list, function(x){
        dpm(newsideoattn2 ~ lag(pidideo), data = x)})`

But I get the error: 
Error: Can't convert NULL to a string
Backtrace:
1. base::lapply(...)
 2. global::FUN(X[[i]], ...)
 3. dpm::dpm(newsideoattn2 ~ lag(pidideo), data = x)
 4. rlang::as_name(enexpr(id))
 5. rlang::as_string(x)
 6. rlang:::abort_coercion(x, "a string")

Do you know why this might be or how I can use dpm with multiply imputed dataframes generally? This same setup works with plm.
Thank you for your time.

Sam

Edit: 
Nevermind I figured out that making the dataframes into panel_data and assigning id and waves resolved the issue. I'm not sure how to delete this comment. Thank you for your time and work in producing such useful packages.

**Comment by jacob-long** [comment]
Hi Sam, no need to delete, I'll "close" the issue. Someone in the future may run into the same problem and benefit from seeing your question (and your answer).
